name: Release

on:
  push:
    tags:
      - '*'
    branches:
      - main
    paths-ignore:
      - README.md
      - catalog.json
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install devbox
        uses: jetify-com/devbox-install-action@734088efddca47cf44ff8a09289c6d0e51b73218 # v0.12.0

      - name: Build and test
        run: |
          devbox run -- make build test-bin lint container test-container

      - name: Login to GitHub Container Registry
        run: |
          devbox run -- bash -c 'echo "${{ github.token }}" | ko login ghcr.io --username "${{ github.actor }}" --password-stdin'

      - name: Release
        run: |
          devbox run -- ./release.sh ${{ github.sha }}
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}

      - name: Create catalog update PR
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ github.token }}
          commit-message: 'Update catalog for build ${{ github.sha }}'
          title: 'Update catalog.json for build ${{ github.sha }}'
          body: |
            Update catalog.json after release of build ${{ github.sha }}
          labels: automated pr
          branch: catalog/update
          delete-branch: true
          add-paths: catalog.json
