name: PR test

on:
  pull_request:
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # tag=v5.0.1
        with:
          go-version-file: "go.mod"
          cache: true

      - name: install kpt
        run: |
          curl -sLO https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.38/kpt_linux_amd64-1.0.0-beta.38.tar.gz
          tar -xzf kpt_linux_amd64-1.0.0-beta.38.tar.gz
          mv kpt /usr/local/bin/

      - name: Build and test
        run: |
          make build test-bin lint container test-container
