name: PR test

on:
  pull_request:
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # tag=v5.0.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: install kpt
        run: |
          curl -sLO https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.38/kpt_linux_amd64-1.0.0-beta.38.tar.gz
          tar -xzf kpt_linux_amd64-1.0.0-beta.38.tar.gz
          mv kpt /usr/local/bin/

      - name: Build and test
        run: |
          make build test-bin lint container test-container
