name: PR test

on:
  pull_request:
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install devbox
        uses: jetify-com/devbox-install-action@734088efddca47cf44ff8a09289c6d0e51b73218 # v0.12.0

      - name: Build and test
        run: |
          devbox run -- make build test-bin lint container test-container
